language: python
python:
    - 3.4
sudo: false
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    - APP_SETTINGS="config.TestingConfig" DATABASE_URL="postgresql://postgres:travis_dev_pass@localhost/travis_ci_test" BARM_SECRET_KEY="yeahthisiswhatweuseinproduction"
before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
install:
    - pip install -r requirements.txt
script:
    - python run_test.py
