language: python
python:
    - 3.4
sudo: false
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    - BARM_SECRET_KEY="yeahthisiswhatweuseinproduction"
before_script:
    - psql -c 'create database BARM_web_test;' -U postgres
install:
    - pip install -r requirements.txt
script:
    - python run_test.py
