language: python
python:
    - 3.4
sudo: false
addons:
    postgresql: "9.4"
services:
    - postgresql
env:
    - BARM_SECRET_KEY="yeahthisiswhatweuseinproduction"
before_script:
    - createdb BARM_web_test -U postgres --echo
install:
    - pip install -r requirements.txt
script:
    - python run_test.py --db "postgresql://postgres:@localhost/BARM_web_test"
