"""empty message

Revision ID: 01b0cbb9a1a7
Revises: 37e499a6b25
Create Date: 2016-04-14 10:29:24.710604

"""

# revision identifiers, used by Alembic.
revision = '01b0cbb9a1a7'
down_revision = '37e499a6b25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_place', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('time_place', sa.Column('longitude', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_place', 'longitude')
    op.drop_column('time_place', 'latitude')
    ### end Alembic commands ###
