"""empty message

Revision ID: 1265912a75
Revises: 15045c53040
Create Date: 2016-01-13 19:11:56.281369

"""

# revision identifiers, used by Alembic.
revision = '1265912a75'
down_revision = '15045c53040'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotation', sa.Column('description', sa.String(length=4000), nullable=True))
    op.create_unique_constraint(None, 'annotation', ['type_identifier'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'annotation', type_='unique')
    op.drop_column('annotation', 'description')
    ### end Alembic commands ###
