"""empty message

Revision ID: 2744a5d51763
Revises: 01b0cbb9a1a7
Create Date: 2016-06-23 10:01:49.722860

"""

# revision identifiers, used by Alembic.
revision = '2744a5d51763'
down_revision = '01b0cbb9a1a7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('taxon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('up_to_superkingdom', sa.String(), nullable=True),
    sa.Column('up_to_phylum', sa.String(), nullable=True),
    sa.Column('up_to_taxclass', sa.String(), nullable=True),
    sa.Column('up_to_order', sa.String(), nullable=True),
    sa.Column('up_to_family', sa.String(), nullable=True),
    sa.Column('up_to_genus', sa.String(), nullable=True),
    sa.Column('up_to_species', sa.String(), nullable=True),
    sa.Column('full_taxonomy', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('gene', sa.Column('taxon_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gene', 'taxon', ['taxon_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gene', type_='foreignkey')
    op.drop_column('gene', 'taxon_id')
    op.drop_table('taxon')
    ### end Alembic commands ###
