"""empty message

Revision ID: 35a7bf1680c1
Revises: afd8ae4de672
Create Date: 2017-05-08 08:45:26.414463

"""

# revision identifiers, used by Alembic.
revision = '35a7bf1680c1'
down_revision = 'afd8ae4de672'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['email'])
    op.drop_column('user', 'name')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    ### end Alembic commands ###
