"""empty message

Revision ID: 37e499a6b25
Revises: 40f48d69b68
Create Date: 2016-04-05 10:15:57.942572

"""

# revision identifiers, used by Alembic.
revision = '37e499a6b25'
down_revision = '40f48d69b68'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('gene_annotation_unique', 'gene_annotation', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('gene_annotation_unique', 'gene_annotation', ['gene_id', 'annotation_id', 'annotation_source_id'])
    ### end Alembic commands ###
