"""empty message

Revision ID: 40f48d69b68
Revises: 1265912a75
Create Date: 2016-03-30 14:12:17.280281

"""

# revision identifiers, used by Alembic.
revision = '40f48d69b68'
down_revision = '1265912a75'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('reference_assembly_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('gene_within_assembly_unique', 'gene', ['name', 'reference_assembly_id'])
    op.drop_constraint('gene_reference_assemlby_id_fkey', 'gene', type_='foreignkey')
    op.create_foreign_key(None, 'gene', 'reference_assembly', ['reference_assembly_id'], ['id'])
    op.drop_column('gene', 'reference_assemlby_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gene', sa.Column('reference_assemlby_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'gene', type_='foreignkey')
    op.create_foreign_key('gene_reference_assemlby_id_fkey', 'gene', 'reference_assembly', ['reference_assemlby_id'], ['id'])
    op.drop_constraint('gene_within_assembly_unique', 'gene', type_='unique')
    op.drop_column('gene', 'reference_assembly_id')
    ### end Alembic commands ###
