"""empty message

Revision ID: 7ce3ce94c8ea
Revises: 2744a5d51763
Create Date: 2016-07-19 17:21:53.894005

"""

# revision identifiers, used by Alembic.
revision = '7ce3ce94c8ea'
down_revision = '2744a5d51763'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_gene_count_gene_id'), 'gene_count', ['gene_id'], unique=False)
    op.create_index(op.f('ix_gene_count_sample_id'), 'gene_count', ['sample_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gene_count_sample_id'), table_name='gene_count')
    op.drop_index(op.f('ix_gene_count_gene_id'), table_name='gene_count')
    ### end Alembic commands ###
