"""empty message

Revision ID: 80f3903961e3
Revises: 9a8e6f2190bb
Create Date: 2017-05-04 10:44:21.077594

"""

# revision identifiers, used by Alembic.
revision = '80f3903961e3'
down_revision = '9a8e6f2190bb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eggnog_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', name='eggnog_category_unique')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eggnog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['annotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_to_sampleset',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('sample_set_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sample_set_id'], ['sample_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('eggnog_to_category',
    sa.Column('eggnog_category_id', sa.Integer(), nullable=True),
    sa.Column('eggnog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['eggnog_category_id'], ['eggnog_category.id'], ),
    sa.ForeignKeyConstraint(['eggnog_id'], ['eggnog.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eggnog_to_category')
    op.drop_table('user_to_sampleset')
    op.drop_table('eggnog')
    op.drop_table('user')
    op.drop_table('eggnog_category')
    ### end Alembic commands ###
