"""empty message

Revision ID: 9a8e6f2190bb
Revises: cfa84823246a
Create Date: 2017-05-03 17:10:23.775362

"""

# revision identifiers, used by Alembic.
revision = '9a8e6f2190bb'
down_revision = 'cfa84823246a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample_set', sa.Column('public', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample_set', 'public')
    ### end Alembic commands ###
