"""empty message

Revision ID: afd8ae4de672
Revises: 80f3903961e3
Create Date: 2017-05-04 19:33:55.288829

"""

# revision identifiers, used by Alembic.
revision = 'afd8ae4de672'
down_revision = '80f3903961e3'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token', sqlalchemy_utils.types.json.JSONType(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth')
    ### end Alembic commands ###
