"""empty message

Revision ID: dfdba5c8095d
Revises: 35a7bf1680c1
Create Date: 2021-02-18 18:04:11.235937

"""

# revision identifiers, used by Alembic.
revision = 'dfdba5c8095d'
down_revision = '35a7bf1680c1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('oauth', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('oauth', 'token',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oauth', 'token',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('oauth', 'provider',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('oauth', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###
